<?php
class UsersController extends AppController
{
	public function beforeFilter()
	{
		parent::beforeFilter(); // TODO: Change the autogenerated stub
	}


	public function login(){

	}

	public function index(){

	}

	public function view(){

	}

	public function logout(){

	}

	public function add(){
		if( $this->request->is('post') ){
			$user = $this->User;
			$user->create();

		}
	}

	public function edit(){

	}

	public function delete(){

	}



}
