<?php
class UsersController extends AppController
{
	public function beforeFilter()
	{
		parent::beforeFilter(); // TODO: Change the autogenerated stub
		$this->Auth->allow('login','add');
	}


	public function login(){

		if($this->request->is('post')){
			if( $this->Auth->login() ){
				return $this->redirect($this->Auth->redirectUrl());
			}
			$this->Flash->error(__("Username or password must have been wrong"));
		}

	}

	public function index(){

	}

	public function view(){

	}

	public function logout(){

	}

	public function add(){

		if( $this->request->is('post') ){
			$user = $this->User;
			$user->create();
			if( $user->save( $this->request->data ) ){

			}
		}
	}

	public function edit(){

	}

	public function delete(){

	}



}
